### ISSUE TITLE
BC break between 9.0 and 9.1 when iterating over LDAPSearchResult

### ISSUE THREAD

**Issue by johannes85** [xp-framework/ldap#15]
There is an behavior change between 9.0 and 9.1 when iteration over a LDAPSearchResult.

For example:
```
$res= $this->search(
  'uid='.ldap_escape($userId, '', LDAP_ESCAPE_DN).', ou=foo, ou=bar, o=baz, c=DE',
  '(|'.$projectFilter.')',
  ['name']
);
foreach ($res as $name) {
}
``` 

In 9.0.0 the foreach is not called.
In 9.1.0 the foreach loop is calld 1 times with $name set to null.

This is caused by: https://github.com/xp-framework/ldap/blob/master/src/main/php/peer/ldap/LDAPSearchResult.class.php#L101 since "$this->entries->first" returns null even if there are no entries.

**Comment by thekid** [comment]
Good catch! The `do ... while` loop should be `while ... do`.

**Comment by thekid** [comment]
Fix released in https://github.com/xp-framework/ldap/releases/tag/v9.1.1. **Sorry for this oversight.**
